name: Ping API Render

on:
  schedule:
    - cron: '*/120 * * * *'  # A cada 2 horas (UTC)
  workflow_dispatch:        # Permite executar manualmente também

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Requisição para manter API ativa
        run: |
          curl -s https://medscan-api-ujft.onrender.com/ping > /dev/null
